version: '3'
services:
  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    volumes:
      - "/home/radimt/projects/casestudy_1:/app"
    environment:
      - WORKDIR=/app
    working_dir: /app
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "/home/radimt/projects/casestudy_1:/app"
    restart: unless-stopped

  dbeaver:
    image: dmitryrck/dbeaver
    ports:
      - "5433:5432"  # Change the port if required
    restart: unless-stopped